#!/usr/bin/env python3
"""
Turns a one-colour artwork (red on a light background) into the app's ASCII art: a character layer plus a solid
layer traced at a finer grid, written as a TypeScript module that src/components/ui/ascii-picture.tsx draws.

    pip install pillow numpy
    python3 scripts/ascii_art.py SOURCE OUT.ts --name RIBS --bg 255,255,255 --crop 0,0,910,2000 --cols 56 --sub 6

How it reads the image: every pixel is placed on the line from the background colour to the red, 0 for paper and
1 for full red. A character cell whose average is below --lo is blank, above --hi it is left to the solid layer,
and anything between picks a character from RAMP (lightest to heaviest). The solid layer marks every fine cell
above --solid, so its edges follow the artwork more closely than whole characters could.
"""
import argparse
import numpy as np
from PIL import Image

RAMP = " .:-=+so*xX%#@MW"
RED = np.array([150, 24, 28], float)


def coverage(path, bg):
    a = np.asarray(Image.open(path).convert('RGB')).astype(float)
    d = RED - np.array(bg, float)
    return np.clip(((a - np.array(bg, float)) @ d) / (d @ d), 0, 1)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('source'); p.add_argument('out')
    p.add_argument('--name', required=True)
    p.add_argument('--bg', default='255,255,255')
    p.add_argument('--crop', help='x0,y0,x1,y1 in source pixels')
    p.add_argument('--cols', type=int, default=56)
    p.add_argument('--sub', type=int, default=6)
    p.add_argument('--lo', type=float, default=0.035)
    p.add_argument('--hi', type=float, default=0.80)
    p.add_argument('--gamma', type=float, default=0.72)
    p.add_argument('--solid', type=float, default=0.62)
    p.add_argument('--note', default='')
    a = p.parse_args()

    t = coverage(a.source, [int(v) for v in a.bg.split(',')])
    if a.crop:
        x0, y0, x1, y1 = (int(v) for v in a.crop.split(','))
        t = t[y0:y1, x0:x1]
    h, w = t.shape
    rows = round(h / ((w / a.cols) / 0.6))  # JetBrains Mono cells are 0.6 as wide as they are tall
    img = Image.fromarray((t * 255).astype(np.uint8))
    cell = np.asarray(img.resize((a.cols, rows), Image.BOX)).astype(float) / 255
    fine = np.asarray(img.resize((a.cols * a.sub, rows * a.sub), Image.BOX)).astype(float) / 255

    text = []
    for r in range(rows):
        line = ''
        for c in range(a.cols):
            v = cell[r, c]
            if v < a.lo or v >= a.hi:
                line += ' '
            else:
                v = ((v - a.lo) / (a.hi - a.lo)) ** a.gamma
                line += RAMP[1 + min(len(RAMP) - 2, int(v * (len(RAMP) - 1)))]
        text.append(line.rstrip())

    runs = []
    for r in range(rows * a.sub):
        on, row, c = fine[r] > a.solid, [], 0
        while c < len(on):
            if on[c]:
                s = c
                while c < len(on) and on[c]:
                    c += 1
                row.append(f'{s}.{c - s}')
            else:
                c += 1
        runs.append(' '.join(row))

    n = a.name
    nl = '\n'
    with open(a.out, 'w') as f:
        f.write(f'''// Generated by scripts/ascii_art.py. {a.note}
// Light cells became characters from "{RAMP[1:]}"; the solid red was traced at {a.sub}x the character grid so its
// edges stay smooth. {a.cols} columns by {rows} rows of 0.6em-wide JetBrains Mono cells.

export const {n}_COLS = {a.cols};
export const {n}_ROWS = {rows};
export const {n}_SUB = {a.sub};

/** The character layer, one line per row. */
export const {n}_TEXT = `
{nl.join(text)}
`.slice(1, -1).split('\\n');

/** The solid layer: per sub-row, runs of "start.length" in sub-columns. */
export const {n}_SOLID = `
{nl.join(runs)}
`.slice(1, -1).split('\\n');
''')
    print(f'{a.out}: {a.cols} x {rows}')


if __name__ == '__main__':
    main()
